replace F:\TLU15T\*.prg    D:\BJDOS\TLU15T     /u
replace F:\TLU15T\*.obj    D:\BJDOS\TLU15T     /u
replace F:\TLU15T\*.exe    D:\BJDOS\TLU15T     /u
replace F:\TLU15T\*.dbf    D:\BJDOS\TLU15T     /u
replace F:\TLU15T\*.ch     D:\BJDOS\TLU15T     /u
replace F:\TLU15T\*.txt    D:\BJDOS\TLU15T     /u
replace F:\TLU15T\*.doc    D:\BJDOS\TLU15T     /u
replace F:\TLU15T\*.clp    D:\BJDOS\TLU15T     /u
replace F:\TLU15T\*.bat    D:\BJDOS\TLU15T     /u




PAUSE
