#define  doa00 0
#define  doa01 1
#define  doa02 2
#define  doa03 3
#define  doa04 4
#define  doa05 5
#define  doa06 6
#define  doa07 7
#define  doa08 8
#define  doa09 32
#define  doa10 32
#define  doa11 32
#define  doa12 32
#define  doa13 32
#define  doa14 32
#define  doa15 32

#define  dob00 9
#define  dob01 10
#define  dob02 11
#define  dob03 12
#define  dob04 13
#define  dob05 16
#define  dob06 16
#define  dob07 23
#define  dob08 24
#define  dob09 25
#define  dob10 26
#define  dob11 27
#define  dob12 12
#define  dob13 14
#define  dob14 31
#define  dob15 15

