#define  doa00 32
#define  doa01 32
#define  doa02 0
#define  doa03 1
#define  doa04 2
#define  doa05 3
#define  doa06 4
#define  doa07 5
#define  doa08 6
#define  doa09 32
#define  doa10 32
#define  doa11 32
#define  doa12 32
#define  doa13 32
#define  doa14 32
#define  doa15 32

#define  dob00 7
#define  dob01 8
#define  dob02 9
#define  dob03 10
#define  dob04 11
#define  dob05 12
#define  dob06 16
#define  dob07 23
#define  dob08 24
#define  dob09 25
#define  dob10 26
#define  dob11 27
#define  dob12 32
#define  dob13 13
#define  dob14 14
#define  dob15 15

