#define  doa00 0
#define  doa01 1
#define  doa02 2
#define  doa03 3
#define  doa04 4
#define  doa05 5
#define  doa06 6
#define  doa07 7
#define  doa08 8
#define  doa09 9
#define  doa10 10
#define  doa11 11
#define  doa12 12
#define  doa13 32
#define  doa14 32
#define  doa15 32

#define  dob00 16 + 0
#define  dob01 16 + 1
#define  dob02 16 + 2
#define  dob03 16 + 3
#define  dob04 16 + 4
#define  dob05 16 + 5
#define  dob06 16 + 6
#define  dob07 16 + 7
#define  dob08 16 + 8
#define  dob09 16 + 9
#define  dob10 16 + 10
#define  dob11 16 + 11
#define  dob12 16 + 12
#define  dob13 13
#define  dob14 14
#define  dob15 15

