/***
*
*  SIO_TXT.CH
*
*  Standard INKEY() key-code definitions
*
*  Copyright (c) 1990-1993, Computer Associates International, Inc.
*  All rights reserved.
*
*  NOTE: Keystroke descriptions marked with an asterick (*) are only
*	 available on enhanced keyboards (those with more than 84 keys)
*
*/


// Cursor movement keys
//®É°T
#define STX	     CHR(2)
#define ETX	     CHR(3)
#define ENQ	     CHR(5)
#define ACK	     CHR(6)
#define NAK	     CHR(7)
//#define EXT	       CHR(3)
//#define EOT	       CHR(4)
//#define NAK	       CHR(21)
//#define VA	       CHR(32)
//#define SA	       CHR(96)

